language: c

compiler:
 - clang
 - gcc

install:
 - mkdir zlib && cd zlib
 - wget http://zlib.net/zlib-1.2.8.tar.gz
 - tar xvxf zlib-1.2.8.tar.gz
 - cd zlib-1.2.8
 - ./configure
 - make
 - sudo make install
 - cd ../..
 - git submodule update --init
 - mkdir build
 - mkdir target
 - cd build

script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=../target
 - make
 - ./bin/test_kmlib
 - ./bin/test_kmlib_static
 - ./bin/bench_kmlib
 - make install
 - test -f ../target/include/kmlib.h
 - test -f ../target/lib/libkm.so
 - test -f ../target/lib/libkm_static.a
