language: c

env:
 - BUILD_TYPE=Release
 - BUILD_TYPE=Debug
 - BUILD_TYPE=Coverage

compiler:
 - clang
 - gcc

install:
 - sudo apt-get install lcov python-pip
 - mkdir zlib && cd zlib
 - wget http://zlib.net/zlib-1.2.8.tar.gz
 - tar xvxf zlib-1.2.8.tar.gz
 - cd zlib-1.2.8
 - ./configure
 - make
 - sudo make install
 - cd ../..
 - sudo pip install cpp-coveralls
 - git submodule update --init
 - mkdir build
 - mkdir target
 - cd build

script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 - make
 - ctest --verbose
 - make install
 - test -f ../target/include/qes.h
 - if [ $static == "TRUE" ] ; then test -f ../target/lib/libqes.a; else test -f ../target/lib/libqes.so ; fi

after_success:
 - cd ..
 - if [ "$BUILD_TYPE" == "Coverage" ] ; then coveralls -e target -e test  -e util -e zlib -E '.*\.h' -e build/CMakeFiles; fi
