# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/prog/kmlib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/prog/kmlib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/prog/kmlib/CMakeFiles /home/kevin/prog/kmlib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/prog/kmlib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named km

# Build rule for target.
km: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 km
.PHONY : km

# fast build rule for target.
km/fast:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/build
.PHONY : km/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f test/CMakeFiles/run.dir/build.make test/CMakeFiles/run.dir/build
.PHONY : run/fast

src/kmfile.o: src/kmfile.c.o
.PHONY : src/kmfile.o

# target to build an object file
src/kmfile.c.o:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/src/kmfile.c.o
.PHONY : src/kmfile.c.o

src/kmfile.i: src/kmfile.c.i
.PHONY : src/kmfile.i

# target to preprocess a source file
src/kmfile.c.i:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/src/kmfile.c.i
.PHONY : src/kmfile.c.i

src/kmfile.s: src/kmfile.c.s
.PHONY : src/kmfile.s

# target to generate assembly for a file
src/kmfile.c.s:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/src/kmfile.c.s
.PHONY : src/kmfile.c.s

src/kmmatch.o: src/kmmatch.c.o
.PHONY : src/kmmatch.o

# target to build an object file
src/kmmatch.c.o:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/src/kmmatch.c.o
.PHONY : src/kmmatch.c.o

src/kmmatch.i: src/kmmatch.c.i
.PHONY : src/kmmatch.i

# target to preprocess a source file
src/kmmatch.c.i:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/src/kmmatch.c.i
.PHONY : src/kmmatch.c.i

src/kmmatch.s: src/kmmatch.c.s
.PHONY : src/kmmatch.s

# target to generate assembly for a file
src/kmmatch.c.s:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/src/kmmatch.c.s
.PHONY : src/kmmatch.c.s

src/kmseq.o: src/kmseq.c.o
.PHONY : src/kmseq.o

# target to build an object file
src/kmseq.c.o:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/src/kmseq.c.o
.PHONY : src/kmseq.c.o

src/kmseq.i: src/kmseq.c.i
.PHONY : src/kmseq.i

# target to preprocess a source file
src/kmseq.c.i:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/src/kmseq.c.i
.PHONY : src/kmseq.c.i

src/kmseq.s: src/kmseq.c.s
.PHONY : src/kmseq.s

# target to generate assembly for a file
src/kmseq.c.s:
	$(MAKE) -f CMakeFiles/km.dir/build.make CMakeFiles/km.dir/src/kmseq.c.s
.PHONY : src/kmseq.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... km"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... run"
	@echo "... src/kmfile.o"
	@echo "... src/kmfile.i"
	@echo "... src/kmfile.s"
	@echo "... src/kmmatch.o"
	@echo "... src/kmmatch.i"
	@echo "... src/kmmatch.s"
	@echo "... src/kmseq.o"
	@echo "... src/kmseq.i"
	@echo "... src/kmseq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

